// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/create-error/create-error.d.ts
declare module 'create-error' {
  // FIXME See Global type references https://github.com/Microsoft/TypeScript/issues/983
  type Err = Error;

  namespace createError {
    interface Error<T extends Err> extends Err {
      new (message?: string, obj?: any): T;
    }
  }

  function createError(): createError.Error<Error>;
  function createError<T extends createError.Error<Error>>(name: string, properties?: any): T;
  function createError<T extends createError.Error<Error>>(Target: createError.Error<Error>, name?: string, properties?: any): T;

  export = createError;
}