// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/2058a1951c4d23ca98d302cd00d51a0bcc528851/password-hash/password-hash.d.ts
declare module 'password-hash' {
    export function generate(password: string, options?: Options): string;
    export function verify(password: string, hashedPassword: string): boolean;
    export function isHashed(password: string): boolean;

    export interface Options {
        algorithm?: string;
        saltLength?: number;
        iterations?: number;
    }
}